import { defineConfig } from "tsup";

// Web Bot Auth (wbauth) TypeScript SDK build config.
// Emit dual ESM/CJS with explicit extensions matching package.json exports:
//   ESM -> dist/index.mjs
//   CJS -> dist/index.js
// `.d.ts` types are generated by tsup from typescript/tsconfig.json.
export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  dts: true,
  outExtension({ format }) {
    return format === "esm" ? { js: ".mjs" } : { js: ".js" };
  },
  clean: true,
});
