/**
 * Multi-key Identity rotation TS coverage (closes Phase 1 vectors.test.ts
 * `it.skip` for retiring_key_jwk vectors per 01-04-SUMMARY hand-off:
 * "Multi-key vector skipped in TS suite — Phase 4's full TS SDK adds
 * multi-key Identity API").
 *
 * Plan 04-01 added Identity.rotate() — this test exercises:
 *   1. rotate() returns a NEW Identity whose active+retiring keys are
 *      correctly placed (active = freshly generated, retiring = the previous
 *      active by kid identity).
 *   2. exportJwks() ordering is [active, retiring] — matches Python
 *      `export_jwks` (RESEARCH §Assumptions A8).
 *   3. Public JWKS never contains the private `d` component (T-04-02-04 —
 *      private bytes do not leak via export, for either active or retiring).
 *   4. Vector 04 fixture sanity: spec/test-vectors/04-multi-uri-jwks/
 *      expected.json has two keys with stable {kty, crv} = {OKP, Ed25519}
 *      and the active kid matches expected.kid — verifies TS and Python
 *      agree on the JWK schema (RFC 7638 fields). Full multi-key
 *      reconstitution from arbitrary JWKs would require an
 *      Identity.fromJwks([active, retiring]) constructor that Plan 04-01
 *      did NOT add per D-58 minimalism (only what's needed for v1).
 */
import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Identity } from "../src/identity.js";
import { loadAllVectors } from "./helpers.js";

const v04 = loadAllVectors().find((v) => v.name === "04-multi-uri-jwks");
if (!v04) throw new Error("vector 04-multi-uri-jwks not found");

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "wbauth-multikey-"));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe("Identity multi-key rotation", () => {
  it("rotate() places previous active key as retiring", async () => {
    const original = await Identity.fromTestKey("https://example.com/agent.json");
    const originalKid = original.kid;
    const rotated = await original.rotate(join(tmp, "rotated.pem"));
    // Active is now the NEW key — kid changed.
    expect(rotated.kid).not.toBe(originalKid);
    const jwks = rotated.exportJwks();
    expect(jwks.keys).toHaveLength(2);
    // Retiring (index 1) is the OLD active by kid identity.
    expect(jwks.keys[1]!.kid).toBe(originalKid);
    // Active (index 0) is the freshly generated key.
    expect(jwks.keys[0]!.kid).toBe(rotated.kid);
  });

  it("retiring key's JWK contains no `d` (private bytes do not leak)", async () => {
    const original = await Identity.fromTestKey("https://example.com/agent.json");
    const rotated = await original.rotate(join(tmp, "leaktest.pem"));
    const jwks = rotated.exportJwks();
    expect(jwks.keys).toHaveLength(2);
    for (const k of jwks.keys) {
      expect(k).not.toHaveProperty("d");
    }
  });

  it("active key JWK has expected RFC 7638 fields {kty, crv, x, kid}", async () => {
    const original = await Identity.fromTestKey("https://example.com/agent.json");
    const rotated = await original.rotate(join(tmp, "fields.pem"));
    const active = rotated.exportJwks().keys[0]!;
    expect(active).toMatchObject({ kty: "OKP", crv: "Ed25519" });
    expect(active).toHaveProperty("x");
    expect(active).toHaveProperty("kid");
    expect(typeof (active as { kid: string }).kid).toBe("string");
    // x is base64url with no padding, fixed length for Ed25519 (32 bytes → 43 chars).
    expect(typeof (active as { x: string }).x).toBe("string");
    expect((active as { x: string }).x.length).toBe(43);
  });

  it("vector 04 fixture: two-key [active, retiring] ordering matches Python output", async () => {
    // Vector 04 expected.json is generated by the Python signer and pinned in
    // CI by the python-vectors workflow (T-04-02-05). This assertion proves
    // TS reads the same fixture shape Python writes — the ordering invariant
    // (active first, retiring second) is the cross-language A8 contract.
    expect(v04.expected.jwks_full).toBeDefined();
    expect(v04.expected.jwks_full!.keys).toHaveLength(2);

    const expectedActive = v04.expected.jwks_full!.keys[0] as JsonWebKey & {
      kid: string;
    };
    const expectedRetiring = v04.expected.jwks_full!.keys[1] as JsonWebKey & {
      kid: string;
    };

    // Active is identified by its kid matching expected.kid (the kid the
    // signature was produced under).
    expect(expectedActive.kid).toBe(v04.expected.kid);
    // Both keys are Ed25519 OKP per RFC 8037.
    expect(expectedActive.kty).toBe("OKP");
    expect(expectedActive.crv).toBe("Ed25519");
    expect(expectedRetiring.kty).toBe("OKP");
    expect(expectedRetiring.crv).toBe("Ed25519");
    // Distinct kids — active and retiring are different keypairs.
    expect(expectedActive.kid).not.toBe(expectedRetiring.kid);
    // Neither public JWK leaks the private `d` component.
    expect(expectedActive).not.toHaveProperty("d");
    expect(expectedRetiring).not.toHaveProperty("d");
  });
});
